name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.27.0
      - run: |
          deno fmt --check *.md **/*.md *.ts **/*.ts
          deno test --allow-env --allow-write --allow-net
